mindmap
  root(("C Data Types & Operators"))
    Data_Types
      Basic
        int
        char
        float
        double
        void
      Type_Modifiers
        short
        long
        signed
        unsigned
      Derived
        Arrays
        Pointers
        Structures
        Unions
        Enums
      Type_Qualifiers
        const
        volatile
        restrict
    Operators
      Arithmetic
        + - * /
        % (modulo)
      Relational
        == != < >
        <= >=
      Logical
        && (AND)
        || (OR)
        ! (NOT)
      Bitwise
        & | ^ ~
        << >>
      Assignment
        = += -= *=
        /= %= &= |=
      Other
        sizeof
        cast (type)
        ?: ternary
        & (address)
        * (dereference)
        -> (member)
    Type_Conversions
      Implicit
        Promotion rules
        Integer promotion
      Explicit
        Cast operator
