mindmap
  root(("C Standard Library & Advanced Topics"))
    Standard_Library
      stdio.h
        printf
        scanf
        fopen / fclose
        fread / fwrite
        fprintf / fscanf
      stdlib.h
        malloc / calloc / realloc / free
        atoi / atof
        qsort / bsearch
        rand / srand
      string.h
        strlen / strcpy
        strcmp / strcat
        strtok / strchr
        memcpy / memset
      math.h
        sin / cos / tan
        sqrt / pow
        log / exp
        fabs / floor / ceil
      ctype.h
        isdigit / isalpha
        isupper / tolower
      time.h
        time / clock
        difftime / mktime
        strftime
      assert.h
        assert(expr)
      signal.h
        signal / raise
      setjmp.h
        setjmp / longjmp
    Advanced_C
      Bit_Manipulation
        Bit fields in structs
        Masking & shifting
      Variadic_Functions
        va_list / va_start
        va_arg / va_end
      Inline_Assembly
        asm("instruction")
      Error_Handling
        errno
        perror
      Multithreading_C11
        thrd_create
        mtx_lock / mtx_unlock
      POSIX_APIs
        fork / exec / wait
        pthreads
        sockets
