package bit_manipulation.questions;

/*
 * 7. FIND THE DIFFERENCE (LeetCode 389)
 *
 * Problem Statement:
 * You are given two strings s and t. String t is generated by random shuffling
 * string s and then add one more letter at a random position. Return the letter
 * that was added to t.
 *
 * Conceptual Understanding:
 * - XOR approach: XOR all characters in s and t, result will be the extra character
 * - XOR is associative and commutative: a ^ a = 0, a ^ 0 = a
 * - Extra character appears once, others appear twice
 * - Time: O(n + m), Space: O(1)
 * - Can also use frequency count or sorting
 * - Bit manipulation gives elegant O(1) space solution
 *
 * Time Complexity: O(n + m)
 * Space Complexity: O(1)
 */

class FindTheDifference7 {

    // Method 1: XOR approach (most efficient)
    public char findTheDifference(String s, String t) {
        char result = 0;

        // XOR all characters in s
        for (char c : s.toCharArray()) {
            result ^= c;
        }

        // XOR all characters in t
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }

    // Method 2: XOR with combined iteration
    public char findTheDifferenceXORCombined(String s, String t) {
        char result = 0;
        int i = 0, j = 0;

        while (i < s.length() && j < t.length()) {
            result ^= s.charAt(i);
            result ^= t.charAt(j);
            i++;
            j++;
        }

        // Add remaining character from t
        while (j < t.length()) {
            result ^= t.charAt(j);
            j++;
        }

        return result;
    }

    // Method 3: Using frequency count
    public char findTheDifferenceFrequency(String s, String t) {
        int[] count = new int[26];

        // Count characters in t
        for (char c : t.toCharArray()) {
            count[c - 'a']++;
        }

        // Subtract characters in s
        for (char c : s.toCharArray()) {
            count[c - 'a']--;
        }

        // Find the character with count 1
        for (int i = 0; i < 26; i++) {
            if (count[i] == 1) {
                return (char) (i + 'a');
            }
        }

        return ' '; // Should not reach here
    }

    // Method 4: Using HashMap
    public char findTheDifferenceHashMap(String s, String t) {
        java.util.Map<Character, Integer> count = new java.util.HashMap<>();

        // Count characters in t
        for (char c : t.toCharArray()) {
            count.put(c, count.getOrDefault(c, 0) + 1);
        }

        // Subtract characters in s
        for (char c : s.toCharArray()) {
            count.put(c, count.get(c) - 1);
            if (count.get(c) == 0) {
                count.remove(c);
            }
        }

        // The remaining character is the extra one
        return count.keySet().iterator().next();
    }

    // Method 5: Sorting approach
    public char findTheDifferenceSort(String s, String t) {
        char[] sChars = s.toCharArray();
        char[] tChars = t.toCharArray();

        java.util.Arrays.sort(sChars);
        java.util.Arrays.sort(tChars);

        for (int i = 0; i < sChars.length; i++) {
            if (sChars[i] != tChars[i]) {
                return tChars[i];
            }
        }

        // Last character in t is the extra one
        return tChars[tChars.length - 1];
    }

    // Method 6: Sum approach
    public char findTheDifferenceSum(String s, String t) {
        int sumS = 0, sumT = 0;

        for (char c : s.toCharArray()) {
            sumS += c;
        }

        for (char c : t.toCharArray()) {
            sumT += c;
        }

        return (char) (sumT - sumS);
    }

    // Method 7: Using streams
    public char findTheDifferenceStream(String s, String t) {
        int[] freq = new int[26];

        t.chars().forEach(c -> freq[c - 'a']++);
        s.chars().forEach(c -> freq[c - 'a']--);

        for (int i = 0; i < 26; i++) {
            if (freq[i] == 1) {
                return (char) (i + 'a');
            }
        }

        return ' ';
    }

    // Method 8: Bit manipulation with XOR and ASCII
    public char findTheDifferenceXORASCII(String s, String t) {
        int result = 0;

        for (char c : s.toCharArray()) {
            result ^= (int) c;
        }

        for (char c : t.toCharArray()) {
            result ^= (int) c;
        }

        return (char) result;
    }

    // Method 9: Using StringBuilder for character counting
    public char findTheDifferenceStringBuilder(String s, String t) {
        java.lang.StringBuilder sb = new java.lang.StringBuilder(t);

        for (char c : s.toCharArray()) {
            int index = sb.indexOf(String.valueOf(c));
            if (index != -1) {
                sb.deleteCharAt(index);
            }
        }

        return sb.charAt(0);
    }

    // Method 10: Recursive approach
    public char findTheDifferenceRecursive(String s, String t) {
        return findTheDifferenceRecursiveHelper(s, t, 0, 0, (char) 0);
    }

    private char findTheDifferenceRecursiveHelper(String s, String t, int i, int j, char xor) {
        // Base case: reached end of both strings
        if (i == s.length() && j == t.length()) {
            return xor;
        }

        // XOR character from s if available
        if (i < s.length()) {
            xor ^= s.charAt(i);
            return findTheDifferenceRecursiveHelper(s, t, i + 1, j, xor);
        }

        // XOR character from t
        xor ^= t.charAt(j);
        return findTheDifferenceRecursiveHelper(s, t, i, j + 1, xor);
    }

    // Method 11: Using LinkedHashMap to preserve order
    public char findTheDifferenceLinkedHashMap(String s, String t) {
        java.util.LinkedHashMap<Character, Integer> count = new java.util.LinkedHashMap<>();

        for (char c : t.toCharArray()) {
            count.put(c, count.getOrDefault(c, 0) + 1);
        }

        for (char c : s.toCharArray()) {
            int current = count.get(c);
            if (current == 1) {
                count.remove(c);
            } else {
                count.put(c, current - 1);
            }
        }

        return count.keySet().iterator().next();
    }

    // Method 12: Bit manipulation with multiple passes
    public char findTheDifferenceBitManipulation(String s, String t) {
        char result = 0;

        // First pass: XOR all characters
        for (char c : s.toCharArray()) {
            result ^= c;
        }
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }

    // Method 13: Using array for counting (more efficient than HashMap)
    public char findTheDifferenceArrayCount(String s, String t) {
        int[] count = new int[26];

        for (char c : t.toCharArray()) {
            count[c - 'a']++;
        }

        for (char c : s.toCharArray()) {
            count[c - 'a']--;
        }

        for (int i = 0; i < 26; i++) {
            if (count[i] > 0) {
                return (char) (i + 'a');
            }
        }

        return ' ';
    }

    // Method 14: Functional approach with reduce
    public char findTheDifferenceReduce(String s, String t) {
        return (char) (t.chars().reduce(0, (a, b) -> a ^ b) ^
                      s.chars().reduce(0, (a, b) -> a ^ b));
    }

    // Method 15: Optimized XOR with single pass concept
    public char findTheDifferenceOptimized(String s, String t) {
        char extra = 0;

        for (int i = 0; i < s.length(); i++) {
            extra ^= s.charAt(i);
            extra ^= t.charAt(i);
        }

        // Add the last character from t
        extra ^= t.charAt(t.length() - 1);

        return extra;
    }

    // Test cases
    public static void main(String[] args) {
        FindTheDifference7 solution = new FindTheDifference7();

        // Test Case 1: Basic test
        String s1 = "abcd", t1 = "abcde";
        System.out.println("s: \"" + s1 + "\", t: \"" + t1 + "\"");
        System.out.println("Extra character: " + solution.findTheDifference(s1, t1)); // Expected: 'e'

        // Test Case 2: Different positions
        String s2 = "a", t2 = "aa";
        System.out.println("\ns: \"" + s2 + "\", t: \"" + t2 + "\"");
        System.out.println("Extra character: " + solution.findTheDifference(s2, t2)); // Expected: 'a'

        // Test Case 3: Longer strings
        String s3 = "ae", t3 = "aea";
        System.out.println("\ns: \"" + s3 + "\", t: \"" + t3 + "\"");
        System.out.println("Extra character: " + solution.findTheDifference(s3, t3)); // Expected: 'a'

        // Test Case 4: Empty s
        String s4 = "", t4 = "y";
        System.out.println("\ns: \"" + s4 + "\", t: \"" + t4 + "\"");
        System.out.println("Extra character: " + solution.findTheDifference(s4, t4)); // Expected: 'y'

        // Test Case 5: Compare different approaches
        String testS = "hello", testT = "helloworld";
        System.out.println("\nComparing approaches for s=\"" + testS + "\", t=\"" + testT + "\"");

        char[] results = {
            solution.findTheDifference(testS, testT),
            solution.findTheDifferenceXORCombined(testS, testT),
            solution.findTheDifferenceFrequency(testS, testT),
            solution.findTheDifferenceHashMap(testS, testT),
            solution.findTheDifferenceSort(testS, testT),
            solution.findTheDifferenceSum(testS, testT),
            solution.findTheDifferenceXORASCII(testS, testT),
            solution.findTheDifferenceReduce(testS, testT)
        };

        String[] methodNames = {
            "XOR", "XOR Combined", "Frequency", "HashMap", "Sort", "Sum", "XOR ASCII", "Reduce"
        };

        for (int i = 0; i < results.length; i++) {
            System.out.println(methodNames[i] + ": '" + results[i] + "'");
        }

        // Verify all methods give same result
        boolean allEqual = true;
        for (int i = 1; i < results.length; i++) {
            if (results[i] != results[0]) {
                allEqual = false;
                break;
            }
        }
        System.out.println("All methods equal: " + allEqual);

        // Test Case 6: Special characters
        String s6 = "abc", t6 = "abcc";
        System.out.println("\nSpecial case s=\"" + s6 + "\", t=\"" + t6 + "\"");
        System.out.println("Extra character: '" + solution.findTheDifference(s6, t6) + "'");

        // Test Case 7: Performance comparison
        StringBuilder longS = new StringBuilder();
        StringBuilder longT = new StringBuilder();

        for (int i = 0; i < 10000; i++) {
            longS.append('a');
            longT.append('a');
        }
        longT.append('b'); // Add extra character

        String perfS = longS.toString();
        String perfT = longT.toString();

        long startTime, endTime;

        startTime = System.nanoTime();
        for (int i = 0; i < 100; i++) {
            solution.findTheDifference(perfS, perfT);
        }
        endTime = System.nanoTime();
        System.out.println("\nXOR approach (100 runs): " + (endTime - startTime) / 1000000 + " ms");

        startTime = System.nanoTime();
        for (int i = 0; i < 100; i++) {
            solution.findTheDifferenceSort(perfS, perfT);
        }
        endTime = System.nanoTime();
        System.out.println("Sort approach (100 runs): " + (endTime - startTime) / 1000000 + " ms");

        // Test Case 8: Unicode characters
        String s8 = "αβγ", t8 = "αβγδ";
        System.out.println("\nUnicode s=\"" + s8 + "\", t=\"" + t8 + "\"");
        System.out.println("Extra character: '" + solution.findTheDifference(s8, t8) + "'");
    }
}