flowchart TB
  NIO[Java NIO Architecture]
  NIO --> B[Buffers]
  NIO --> C[Channels]
  NIO --> S[Selectors]

  B --> BT[Buffer Types]
  BT --> BB[ByteBuffer]
  BT --> CB[CharBuffer]
  BT --> IB[IntBuffer]
  BT --> LB[LongBuffer]
  BT --> FB[FloatBuffer]
  BT --> DB[DoubleBuffer]
  B --> BP[Buffer Properties]
  BP --> CAP[Capacity]
  BP --> POS[Position]
  BP --> LIM[Limit]
  BP --> MARK[Mark]
  B --> BO[Buffer Operations]
  BO --> FLIP[flip]
  BO --> REWIND[rewind]
  BO --> CLEAR[clear]
  BO --> COMPACT[compact]
  B --> DBUF[Direct vs Heap]
  DBUF --> D[Direct Buffer]
  DBUF --> H[Heap Buffer]

  C --> CT[Channel Types]
  CT --> FC[FileChannel]
  CT --> SC[SocketChannel]
  CT --> SSC[ServerSocketChannel]
  CT --> DC[DatagramChannel]
  C --> CO[Channel Operations]
  CO --> READ[read into Buffer]
  CO --> WRITE[write from Buffer]
  CO --> TRANSFER[transferTo / transferFrom]
  CO --> MMAP[memory-mapped files]

  S --> SEL[Selector]
  SEL --> REG[register Channels]
  SEL --> SELK[SelectionKey]
  SEL --> SELN[select]
  SEL --> SELS[selectedKeys]

  NIO --> SCATTER[Scatter / Gather I/O]
  NIO --> NIO2[NIO.2 File System]
  NIO2 --> PATH[Path]
  NIO2 --> FS[FileSystem]
  NIO2 --> WDS[WatchService]
  NIO2 --> ATTR[File Attributes]

  NIO --> HTTP[HttpClient Java 11+]
  HTTP --> SYN[HttpClient.send]
  HTTP --> ASYNC[HttpClient.sendAsync]
  HTTP --> WC[WebSocket]

  NIO --> AIO[Asynchronous I/O]
  AIO --> ACH[AsynchronousFileChannel]
  AIO --> ASC[AsynchronousSocketChannel]
  AIO --> COMP[CompletionHandler]
  AIO --> FUT[Future-based]
