flowchart TB
  SBT[Spring Boot Testing]
  SBT --> BST[Bootstrapping]
  BST --> SST[SpringBootTest]
  SST --> WEB[Web Environment]
  WEB --> MOCK[MOCK]
  WEB --> RP[RANDOM_PORT]
  WEB --> DP[DEFINED_PORT]
  WEB --> NONE[NONE]

  SBT --> SLICE[Test Slices]
  SLICE --> WC[WebMvcTest]
  SLICE --> DC[DataJpaTest]
  SLICE --> JDT[JdbcTest]
  SLICE --> RDT[RestClientTest]
  SLICE --> JDT2[JsonTest]

  SBT --> HTTP[HTTP Testing]
  HTTP --> TRT[TestRestTemplate]
  TRT --> GET[getForEntity]
  TRT --> POST[postForEntity]
  TRT --> EX[exchange]
  HTTP --> WTC[WebTestClient]
  WTC --> GET2[get]
  WTC --> POST2[post]
  WTC --> EXCH[exchange / expectStatus]

  SBT --> CTX[Context Features]
  CTX --> OVP[Override Properties]
  CTX --> MB[MockBean]
  CTX --> MB2[MockitoBean]
  CTX --> DB[TestDatabase]
  CTX --> ATX[ActiveProfiles]

  SBT --> ASS[Assertions]
  ASS --> AJ[AssertJ]
  ASS --> JC[JSON Assert]
  ASS --> MC[MockMvc]
  MC --> PERFORM[perform]
  MC --> EXPR[andExpect]
  MC --> JSON[andExpect jsonPath]

  SBT --> MOCKS[Outgoing Mocks]
  MOCKS --> WMC[WebMock / WireMock]
  MOCKS --> OKH[OkHttp MockWebServer]
