import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  placementSidebar: [
    {
      type: 'autogenerated',
      dirName: 'placement',
    },
  ],
  coursesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'courses',
    },
  ],
};

export default sidebars;
