import fs from 'fs';
import path from 'path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  placementSidebar: [
    {
      type: 'autogenerated',
      dirName: 'courses/ai-engineering-placement',
    },
  ],
};

const coursesDir = path.resolve(process.cwd(), 'docs', 'courses');
if (fs.existsSync(coursesDir)) {
  for (const dir of fs.readdirSync(coursesDir)) {
    const full = path.join(coursesDir, dir);
    if (!fs.statSync(full).isDirectory()) continue;
    if (dir === 'ai-engineering-placement') continue;
    (sidebars as Record<string, unknown>)[`course-${dir}`] = [
      {
        type: 'autogenerated',
        dirName: `courses/${dir}`,
      },
    ];
  }
}

export default sidebars;
