mindmap
  root((Software Quality Management))
    Quality Concepts
      Quality Assurance
      Quality Control
      Quality Planning
      Quality Improvement
    Standards & Models
      ISO 9001
        Quality Management Principles
        Process Approach
        Continuous Improvement
      CMMI
        Maturity Level 1 - Initial
        Maturity Level 2 - Managed
        Maturity Level 3 - Defined
        Maturity Level 4 - Quantitatively Managed
        Maturity Level 5 - Optimizing
      Six Sigma
        DMAIC
        DMADV
        Defect Reduction
    Quality Metrics
      Product Metrics
        Defect Density
        Mean Time To Failure
        Customer Satisfaction
      Process Metrics
        Defect Removal Efficiency
        Process Cycle Time
        Rework Effort
      Project Metrics
        Cost Performance
        Schedule Variance
    Reviews & Inspections
      Walkthroughs
      Technical Reviews
      Inspections
        Planning
        Overview
        Preparation
        Meeting
        Rework
        Follow-Up
    Testing
      Unit Testing
      Integration Testing
      System Testing
      Acceptance Testing
      Regression Testing
