mindmap
  root((Design Patterns))
    Creational
      Singleton
      Factory Method
      Abstract Factory
      Builder
      Prototype
    Structural
      Adapter
      Bridge
      Composite
      Decorator
      Facade
      Flyweight
      Proxy
    Behavioral
      Strategy
      Observer
      Command
      Iterator
      State
      Template Method
      Chain of Responsibility
      Mediator
      Memento
      Visitor
    Concurrency
      Read-Write Lock
      Thread Pool
      Producer-Consumer
      Barrier
      Future/Promise
