mindmap
  root((Distributed Data Structures))
    Caches
      Redis Cache
      Memcached
      CDN Edge Cache
      Write-Through Cache
      Write-Back Cache
      Cache-Aside
    Search Indexes
      Inverted Index
      Elasticsearch
      Trie / Autocomplete
      Bloom Filter
      HyperLogLog
    Count-Min Sketch
    Distributed Counters
      CRDT Counters
      PN-Counter
      G-Counter
    Consistent Hashing
    Merkle Trees
    Gossip Protocol State
