$base = "C:\xampp\htdocs\ai-engineering-journey\docs\courses\software-engineering"
$utf8 = [System.Text.Encoding]::UTF8

# ===== 13-security-engineering.md =====
$path = Join-Path $base "13-security-engineering.md"
$c = [System.IO.File]::ReadAllText($path, $utf8)
$c = $c.Replace("# Security Engineering`n`n", "# Security Engineering`n`n> **Previous:** [DevOps and CI/CD](./12-devops-cicd.md) | **Next:** [Formal Methods](./14-formal-methods.md)`n`n")
$o = "and describe penetration testing methodology."
$g = "`n`n## Chapter at a Glance`n`n| Topic | Key Insight | Practical Takeaway |`n|-------|-------------|-------------------|`n| CIA Triad | Confidentiality, Integrity, Availability | Plus authentication, authorisation, non-repudiation |`n| SDL | Security integrated throughout lifecycle | Retrofitting security is far more expensive |`n| Threat Modelling | STRIDE and attack trees | Apply STRIDE to each component via DFD |`n| OWASP Top 10 | Most critical web vulnerabilities | Injection, XSS, Broken Auth are top risks |`n| Pen Testing | Simulate real attacks | White-box or black-box, internal or external |`n`n## Chapter Roadmap`n`n```mermaid`nflowchart LR`n    A[Security Engineering] --> B[CIA Triad]`n    A --> C[SDL]`n    A --> D[Threat Modelling]`n    A --> E[OWASP Top 10]`n    A --> F[Cryptography]`n    A --> G[Pen Testing]`n    D --> H[STRIDE]`n    D --> I[Attack Trees]`n    E --> J[Injection XSS Broken Auth]`n```"
$c = $c.Replace($o, $o + $g)
$c = $c.Replace("### Security as an Engineering Discipline`n`nSecurity engineering is the discipline", "> **One-Sentence Takeaway:** Security must be engineered from the start; retrofitting is more expensive and less effective.`n`n### Security as an Engineering Discipline`n`nSecurity engineering is the discipline")
$c = $c.Replace("### The Secure Development Lifecycle`n`nThe Secure Development Lifecycle (SDL) integrates security", "> **One-Sentence Takeaway:** Microsofts SDL integrates training, requirements, design, implementation, verification, release, and response.`n`n### The Secure Development Lifecycle`n`nThe Secure Development Lifecycle (SDL) integrates security")
$c = $c.Replace("### Threat Modelling`n`nThreat modelling is a structured approach", "> **Pro Tip:** STRIDE is most effective when applied to data flow diagrams - analyse each element (process, data store, flow) against all six threat categories.`n`n> **One-Sentence Takeaway:** STRIDE covers Spoofing, Tampering, Repudiation, Information Disclosure, DoS, and Elevation of Privilege.`n`n### Threat Modelling`n`nThreat modelling is a structured approach")
$c = $c.Replace("### Security Patterns`n`nSecurity patterns are reusable solutions", "> **One-Sentence Takeaway:** Security patterns include Single Access Point, Check Point, Secure Session, RBAC, and Secure Factory.`n`n### Security Patterns`n`nSecurity patterns are reusable solutions")
$c = $c.Replace("### OWASP Top 10`n`nThe OWASP Top 10 is a widely referenced list", "> **Warning:** Injection and XSS remain the most prevalent web vulnerabilities after two decades - validate input and encode output everywhere.`n`n> **One-Sentence Takeaway:** The OWASP Top 10 covers Injection, Broken Auth, XSS, XXE, Broken Access Control, and more.`n`n### OWASP Top 10`n`nThe OWASP Top 10 is a widely referenced list")
$c = $c.Replace("### Input Validation`n`nInput validation is the first line of defence", "> **One-Sentence Takeaway:** Positive validation (accept known-good) is safer than negative validation (reject known-bad).`n`n### Input Validation`n`nInput validation is the first line of defence")
$c = $c.Replace("### Authentication and Authorisation`n`nAuthentication verifies the identity", "> **One-Sentence Takeaway:** Multi-factor authentication combines something you know, have, and are; RBAC and ABAC control authorisation.`n`n### Authentication and Authorisation`n`nAuthentication verifies the identity")
$c = $c.Replace("### Cryptography in Software`n`nCryptography provides the technical foundation", "> **Remember:** Never implement your own cryptographic algorithms - use well-vetted libraries and manage keys in HSMs.`n`n> **One-Sentence Takeaway:** Symmetric (AES) for bulk encryption, asymmetric (RSA/ECC) for key exchange, hashing (SHA-256) for integrity.`n`n### Cryptography in Software`n`nCryptography provides the technical foundation")
$c = $c.Replace("### Penetration Testing`n`nPenetration testing simulates real-world attacks", "> **One-Sentence Takeaway:** Pen testing follows: reconnaissance, enumeration, vulnerability analysis, exploitation, post-exploitation, reporting.`n`n### Penetration Testing`n`nPenetration testing simulates real-world attacks")
$s = "## Summary`n`nSecurity engineering embeds"
$r = "## Concept Comparison Table`n`n| Threat Category | STRIDE Element | Example | Mitigation |`n|----------------|----------------|---------|------------|`n| Spoofing | Identity | Impersonate user | MFA |`n| Tampering | Data | Modify request | TLS, signing |`n| Repudiation | Audit | Deny action | Audit logs |`n| Info Disclosure | Confidentiality | Leak credentials | Encryption |`n| Denial of Service | Availability | Flood endpoint | Rate limiting |`n| Elevation of Privilege | Access | Escalate to admin | Server-side auth |`n`n## Quick Reference`n`n| Concept | Definition | Best Practice |`n|---------|------------|---------------|`n| CIA Triad | Confidentiality, Integrity, Availability | Defence in depth |`n| SDL | Secure Development Lifecycle | Security in every phase |`n| STRIDE | Six threat categories | Model via DFD |`n| OWASP Top 10 | Top web vulnerabilities | Regular scanning and testing |`n| Positive Validation | Accept known-good input | Whitelist over blacklist |`n| MFA | Multi-factor authentication | Use wherever possible |`n| HSM | Hardware Security Module | Tamper-resistant key storage |`n`n## Cross-Application Matrix`n`n| Application Type | Key Threat | Primary Defence |`n|-----------------|------------|-----------------|`n| Web application | Injection, XSS | Input validation, output encoding |`n| Mobile app | Broken auth, data leakage | MFA, encrypted storage |`n| Cloud service | Misconfiguration | IaC scanning, least privilege |`n| IoT device | Physical tampering | Secure boot, encrypted firmware |`n| Financial system | Fraud, data breach | Strong auth, audit logs, encryption |`n`n## Chapter Quiz`n`n1. What does the S in STRIDE stand for?`n   A) Secure`n   B) Spoofing`n   C) Session`n   D) Scanning`n`n<details><summary>Answer</summary>**B)** S stands for Spoofing - impersonating a user or system.</details>`n`n2. Which OWASP vulnerability involves untrusted data in web pages?`n   A) SQL Injection`n   B) XSS`n   C) XXE`n   D) Broken Access Control`n`n<details><summary>Answer</summary>**B)** Cross-Site Scripting (XSS) occurs when untrusted data is included in web pages without proper escaping.</details>`n`n3. What is the recommended approach for password storage?`n   A) Encrypt passwords with AES`n   B) Store hashed with salt using bcrypt or Argon2`n   C) Store in plaintext with access control`n   D) Use reversible encryption`n`n<details><summary>Answer</summary>**B)** Passwords should be hashed with a salt using algorithms like bcrypt or Argon2 - never stored in plaintext or encrypted.</details>`n`n## Summary`n`nSecurity engineering embeds"
$c = $c.Replace($s, $r)
[System.IO.File]::WriteAllText($path, $c, $utf8)
Write-Host "OK 13-security-engineering.md"

# ===== 14-formal-methods.md =====
$path = Join-Path $base "14-formal-methods.md"
$c = [System.IO.File]::ReadAllText($path, $utf8)
$c = $c.Replace("# Formal Methods`n`n", "# Formal Methods`n`n> **Previous:** [Security Engineering](./13-security-engineering.md) | **Next:** [Software Metrics](./15-metrics.md)`n`n")
$o = "and describe the application of formal methods in safety-critical systems."
$g = "`n`n## Chapter at a Glance`n`n| Topic | Key Insight | Practical Takeaway |`n|-------|-------------|-------------------|`n| Role of Formal Methods | Mathematical specification and verification | Essential for safety-critical systems |`n| Z Notation | Set theory + predicate logic schemas | Precise specification with schema calculus |`n| Model Checking | Exhaustive state space verification | Automatic but suffers state explosion |`n| Theorem Proving | User-guided logical inference | Handles infinite state spaces |`n| Hoare Logic | Program correctness proofs | Loop invariants are the key challenge |`n`n## Chapter Roadmap`n`n```mermaid`nflowchart LR`n    A[Formal Methods] --> B[Formal Specification]`n    A --> C[Formal Verification]`n    A --> D[Correctness Proofs]`n    A --> E[Refinement]`n    B --> F[Z Notation]`n    B --> G[VDM]`n    B --> H[B-Method]`n    C --> I[Model Checking]`n    C --> J[Theorem Proving]`n    I --> K[SPIN NuSMV]`n    J --> L[Coq Isabelle Z3]`n```"
$c = $c.Replace($o, $o + $g)
$c = $c.Replace("### The Role of Formal Methods`n`nFormal methods are mathematically based techniques", "> **One-Sentence Takeaway:** Formal methods enable precise specification and exhaustive verification - essential when failure is catastrophic.`n`n### The Role of Formal Methods`n`nFormal methods are mathematically based techniques")
$c = $c.Replace("### Formal Specification`n`nFormal specification uses mathematical notation", "> **One-Sentence Takeaway:** Formal specification uses mathematics to describe what a system does, enabling analysis before implementation.`n`n### Formal Specification`n`nFormal specification uses mathematical notation")
$c = $c.Replace("### Formal Verification`n`nFormal verification uses mathematical reasoning", "> **Pro Tip:** Use model checking for finite-state verification (automatic, counterexamples) and theorem proving for infinite/logic properties (requires expertise).`n`n> **One-Sentence Takeaway:** Model checking is automatic but limited by state space; theorem proving handles complexity but requires user guidance.`n`n### Formal Verification`n`nFormal verification uses mathematical reasoning")
$c = $c.Replace("### Correctness Proofs and Hoare Logic`n`nHoare logic provides a formal system", "> **One-Sentence Takeaway:** The Hoare triple P C Q with loop invariants proves partial and total correctness of programs.`n`n### Correctness Proofs and Hoare Logic`n`nHoare logic provides a formal system")
$c = $c.Replace("### Abstraction and Refinement`n`nAbstraction and refinement are complementary concepts", "> **One-Sentence Takeaway:** Refinement transforms abstract specifications to concrete implementations while preserving correctness.`n`n### Abstraction and Refinement`n`nAbstraction and refinement are complementary concepts")
$c = $c.Replace("### Applications in Safety-Critical Systems`n`nFormal methods are mandated or strongly recommended", "> **Remember:** Formal methods are already mandated in railway (CENELEC EN 50128) and avionics (DO-178C) - not theoretical, but proven in practice.`n`n> **One-Sentence Takeaway:** Formal methods are mandated in railway signalling and avionics; Paris Metro Line 14 used B-Method.`n`n### Applications in Safety-Critical Systems`n`nFormal methods are mandated or strongly recommended")
$s = "## Summary`n`nFormal methods apply mathematical"
$r = "## Concept Comparison Table`n`n| Technique | Approach | Automation | State Space | Best For |`n|-----------|----------|------------|-------------|----------|`n| Model Checking | State space exploration | Fully automatic | Finite only | Concurrent, reactive systems |`n| Theorem Proving | Logical inference | User-guided | Infinite | Complex data structures |`n| Hoare Logic | Pre/post-condition reasoning | Manual | Any | Program correctness proofs |`n| Z Notation | Set theory schemas | Syntax checking | N/A | System specification |`n| B-Method | Refinement calculus | Proof obligation generation | N/A | Code generation from spec |`n`n## Quick Reference`n`n| Concept | Definition | Example |`n|---------|------------|---------|`n| Hoare Triple | P C Q | n >= 0 fact = n! |`n| Loop Invariant | Holds before/after each iteration | f = (i-1)! |`n| Refinement | Abstract to concrete | Replace set with array |`n| State Explosion | Exponential state growth | 25 Boolean vars = 33M states |`n| Proof Obligation | Condition to prove correctness | Invariant preservation |`n`n## Cross-Application Matrix`n`n| Domain | Formal Method | Standard | Real-World Use |`n|--------|---------------|----------|-----------------|`n| Railway | B-Method | EN 50128 | Paris Metro Line 14 |`n| Avionics | Model checking + proof | DO-178C | Airbus A380 flight controls |`n| Crypto | Theorem proving | N/A | TLS handshake verification |`n| Medical | Refinement | IEC 62304 | Insulin pump design |`n| Nuclear | Z + model checking | IEC 61513 | Reactor protection systems |`n`n## Chapter Quiz`n`n1. What is the main limitation of model checking?`n   A) Cannot handle temporal logic`n   B) State explosion problem`n   C) Requires user guidance`n   D) Only for sequential programs`n`n<details><summary>Answer</summary>**B)** Model checking suffers from state explosion - the number of states grows exponentially with concurrent components.</details>`n`n2. What does a Hoare triple P C Q represent?`n   A) Program C computes Q given P`n   B) If P holds before C, Q holds after C`n   C) P and Q are equivalent`n   D) C is a refinement of P to Q`n`n<details><summary>Answer</summary>**B)** A Hoare triple states that if precondition P holds before execution of command C, then postcondition Q holds after.</details>`n`n3. Which standard mandates formal methods for railway signalling?`n   A) DO-178C`n   B) ISO 26262`n   C) CENELEC EN 50128`n   D) IEC 61508`n`n<details><summary>Answer</summary>**C)** CENELEC EN 50128 requires formal methods for the highest railway safety integrity levels.</details>`n`n## Summary`n`nFormal methods apply mathematical"
$c = $c.Replace($s, $r)
[System.IO.File]::WriteAllText($path, $c, $utf8)
Write-Host "OK 14-formal-methods.md"

# ===== 15-metrics.md =====
$path = Join-Path $base "15-metrics.md"
$c = [System.IO.File]::ReadAllText($path, $utf8)
$c = $c.Replace("# Software Metrics`n`n", "# Software Metrics`n`n> **Previous:** [Formal Methods](./14-formal-methods.md) | **Next:** [Capstone Project](./16-capstone.md)`n`n")
$o = "and interpret metric data to support decision making."
$g = "`n`n## Chapter at a Glance`n`n| Topic | Key Insight | Practical Takeaway |`n|-------|-------------|-------------------|`n| Product Metrics | LOC, cyclomatic complexity, Halstead, FP, OO | Cyclomatic complexity should not exceed 10 per module |`n| Process Metrics | DRE, process maturity | DRE targets 95%+ for mature processes |`n| Project Metrics | EVM, burn-down, burn-up | SPI < 1 behind schedule; CPI < 1 over budget |`n| Applying Metrics | GQM approach aligns metrics with goals | Measure for decisions, not evaluation |`n`n## Chapter Roadmap`n`n```mermaid`nflowchart LR`n    A[Software Metrics] --> B[Product Metrics]`n    A --> C[Process Metrics]`n    A --> D[Project Metrics]`n    B --> E[LOC]`n    B --> F[Cyclomatic Complexity]`n    B --> G[Halstead]`n    B --> H[Function Points]`n    B --> I[OO Metrics]`n    C --> J[DRE]`n    C --> K[CMMI Maturity]`n    D --> L[EVM]`n    D --> M[Burn-Down Burn-Up]`n```"
$c = $c.Replace($o, $o + $g)
$c = $c.Replace("### The Purpose of Software Measurement`n`nSoftware measurement is the process", "> **One-Sentence Takeaway:** Measurement provides quantitative basis for understanding, controlling, and improving software development.`n`n### The Purpose of Software Measurement`n`nSoftware measurement is the process")
$c = $c.Replace("### Product Metrics`n`nProduct metrics quantify characteristics", "> **Pro Tip:** Cyclomatic complexity under 10 is the industry guideline - modules above 15 should be refactored or receive intensive testing.`n`n> **One-Sentence Takeaway:** Product metrics measure size (LOC, FP) and complexity (cyclomatic, Halstead, OO).`n`n### Product Metrics`n`nProduct metrics quantify characteristics")
$c = $c.Replace("### Process Metrics`n`nProcess metrics measure attributes", "> **One-Sentence Takeaway:** Defect removal efficiency (DRE) measures the proportion of defects found before delivery.`n`n### Process Metrics`n`nProcess metrics measure attributes")
$c = $c.Replace("### Project Metrics`n`nProject metrics track the progress", "> **One-Sentence Takeaway:** EVM integrates scope, schedule, and cost; burn-down/burn-up charts track agile progress with scope visibility.`n`n### Project Metrics`n`nProject metrics track the progress")
$c = $c.Replace("### Applying Metrics`n`nMetrics should be collected consistently", "> **Remember:** Never use individual metrics for performance evaluation - Goodharts law: when a measure becomes a target, it ceases to be a good measure.`n`n> **One-Sentence Takeaway:** GQM aligns metrics with goals; metrics must be interpreted in context and used to support, not replace, judgment.`n`n### Applying Metrics`n`nMetrics should be collected consistently")
$s = "## Summary`n`nSoftware metrics provide quantitative"
$r = "## Concept Comparison Table`n`n| Metric | Category | What It Measures | Formula/How | Threshold |`n|--------|----------|-----------------|-------------|-----------|`n| LOC | Product | Code size | Source line count | N/A |`n| Cyclomatic Complexity | Product | Control flow complexity | M = E - N + 2P | < 10 per module |`n| Halstead Volume | Product | Implementation size | V = N log2(n) | N/A |`n| Function Points | Product | Functional size | Weighted function types | N/A |`n| WMC | Product (OO) | Methods per class | Count methods | < 20 |`n| DIT | Product (OO) | Inheritance depth | Inheritance chain length | < 5 |`n| DRE | Process | Defect detection effectiveness | DRE = dev defects / total | > 95% |`n| CPI | Project | Cost efficiency | EV / AC | >= 1.0 |`n| SPI | Project | Schedule efficiency | EV / PV | >= 1.0 |`n`n## Quick Reference`n`n| Concept | Definition | Application |`n|---------|------------|-------------|`n| GQM | Goal-Question-Metric | Align metrics with goals |`n| DRE | Defect Removal Efficiency | Measure quality process |`n| EVA | Earned Value Analysis | Integrated project tracking |`n| MTTF | Mean Time To Failure | Reliability metric |`n| MTTR | Mean Time To Repair | Maintenance metric |`n| LCOM | Lack of Cohesion of Methods | OO cohesion metric |`n`n## Cross-Application Matrix`n`n| Goal | Question | Metric | Decision |`n|------|----------|--------|----------|`n| Improve quality | How many defects in testing? | Defect density | Focus testing on high-density modules |`n| Reduce complexity | Which modules are too complex? | Cyclomatic complexity | Refactor modules > 15 |`n| Track project health | Are we on schedule? | SPI, burn-down | Adjust resources or scope |`n| Improve testing | Is testing effective? | DRE | Improve review and testing process |`n| Manage OO design | Are classes well-structured? | WMC, DIT, CBO, LCOM | Redesign problematic classes |`n`n## Chapter Quiz`n`n1. What does a cyclomatic complexity of 10 imply?`n   A) The module has 10 lines of code`n   B) 10 test cases needed for branch coverage`n   C) The module has 10 decision points`n   D) Both B and C`n`n<details><summary>Answer</summary>**D)** Cyclomatic complexity equals decision points + 1, so 9 decision points gives M=10, requiring 10 tests for branch coverage.</details>`n`n2. What does CPI > 1.0 indicate?`n   A) Behind schedule`n   B) Under budget`n   C) Over budget`n   D) Over-scoped`n`n<details><summary>Answer</summary>**B)** CPI (Cost Performance Index) > 1.0 means earned value exceeds actual cost - the project is under budget.</details>`n`n3. What is the industry recommended maximum for cyclomatic complexity per module?`n   A) 5`n   B) 10`n   C) 20`n   D) 50`n`n<details><summary>Answer</summary>**B)** The industry guideline recommends cyclomatic complexity should not exceed 10 per module.</details>`n`n## Summary`n`nSoftware metrics provide quantitative"
$c = $c.Replace($s, $r)
[System.IO.File]::WriteAllText($path, $c, $utf8)
Write-Host "OK 15-metrics.md"

# ===== 16-capstone.md =====
$path = Join-Path $base "16-capstone.md"
$c = [System.IO.File]::ReadAllText($path, $utf8)
$c = $c.Replace("# Capstone Project`n`n", "# Capstone Project`n`n> **Previous:** [Software Metrics](./15-metrics.md) | **Next:** None`n`n")
$o = "This chapter integrates all previous chapters into a single, cohesive project exercise."
$g = "`n`n## Chapter at a Glance`n`n| Topic | Key Insight | Practical Takeaway |`n|-------|-------------|-------------------|`n| Project Planning | WBS, estimation, schedule, risk | Foundation for all subsequent phases |`n| Requirements | IEEE 830 SRS with use case models | Stakeholder interviews and surveys |`n| Architecture | ADD method with ADRs | Pattern selection justified by drivers |`n| Implementation | Agile Sprint with TDD | Unit test coverage minimum 70% |`n| Testing | Multi-level strategy with traceability | BVA, equivalence partitioning, decision tables |`n| QA Plan | Metrics, reviews, configuration management | DRE > 90%, code review 100% of new code |`n| Deployment | CI/CD pipeline with rollback | Blue-green or canary strategy |`n`n## Chapter Roadmap`n`n```mermaid`nflowchart LR`n    A[Capstone Project] --> B[Phase 1 Planning]`n    A --> C[Phase 2 Requirements]`n    A --> D[Phase 3 Architecture]`n    A --> E[Phase 4 Implementation]`n    A --> F[Phase 5 Testing]`n    A --> G[Phase 6 QA]`n    A --> H[Phase 7 Deployment]`n    B --> I[WBS Charter Estimate]`n    C --> J[IEEE 830 Use Cases]`n    D --> K[ADD ADRs]`n    E --> L[Sprint TDD]`n    F --> M[Unit System Acceptance]`n    G --> N[Metrics Reviews]`n    H --> O[CI/CD Rollback]`n```"
$c = $c.Replace($o, $o + $g)
$c = $c.Replace("### Capstone Overview`n`nThe capstone project requires the student", "> **One-Sentence Takeaway:** The capstone integrates all software engineering knowledge areas into a single Smart Campus Management System project.`n`n### Capstone Overview`n`nThe capstone project requires the student")
$c = $c.Replace("## Phase 1: Project Planning`n`n### Objective`n`nProduce a comprehensive project plan", "> **Pro Tip:** The quality of your WBS and risk register in Phase 1 determines the success of all subsequent phases - invest time here.`n`n> **One-Sentence Takeaway:** Phase 1 produces a project charter, WBS, estimation, schedule, risk register, and team structure.`n`n## Phase 1: Project Planning`n`n### Objective`n`nProduce a comprehensive project plan")
$c = $c.Replace("## Phase 2: Requirements Specification`n`n### Objective`n`nProduce a complete Software Requirements Specification", "> **One-Sentence Takeaway:** Phase 2 delivers an IEEE 830 SRS with use case diagrams, traceability matrix, and MoSCoW prioritisation.`n`n## Phase 2: Requirements Specification`n`n### Objective`n`nProduce a complete Software Requirements Specification")
$c = $c.Replace("## Phase 3: Architectural Design`n`n### Objective`n`nProduce an architectural design", "> **One-Sentence Takeaway:** Phase 3 applies Attribute-Driven Design with UML diagrams, ADRs, and architecture evaluation against quality attributes.`n`n## Phase 3: Architectural Design`n`n### Objective`n`nProduce an architectural design")
$c = $c.Replace("## Phase 4: Implementation Sprint`n`n### Objective`n`nImplement one subsystem", "> **One-Sentence Takeaway:** Phase 4 runs a two-week Sprint with user stories, TDD, 70%+ coverage, and a Sprint review and retrospective.`n`n## Phase 4: Implementation Sprint`n`n### Objective`n`nImplement one subsystem")
$c = $c.Replace("## Phase 5: Testing Strategy`n`n### Objective`n`nDesign and document a comprehensive testing strategy", "> **One-Sentence Takeaway:** Phase 5 defines test levels, white-box/black-box techniques, automation approach, and non-functional testing.`n`n## Phase 5: Testing Strategy`n`n### Objective`n`nDesign and document a comprehensive testing strategy")
$c = $c.Replace("## Phase 6: Quality Assurance Plan`n`n### Objective`n`nProduce a quality assurance plan", "> **One-Sentence Takeaway:** Phase 6 specifies quality standards, reviews, metrics targets (DRE > 90%), and configuration management.`n`n## Phase 6: Quality Assurance Plan`n`n### Objective`n`nProduce a quality assurance plan")
$c = $c.Replace("## Phase 7: Deployment Plan`n`n### Objective`n`nProduce a deployment plan", "> **One-Sentence Takeaway:** Phase 7 defines deployment architecture, CI/CD pipeline, rollback procedures, and go-live checklist.`n`n## Phase 7: Deployment Plan`n`n### Objective`n`nProduce a deployment plan")
$s = "## Summary`n`nThe capstone project integrates"
$r = "## Concept Comparison Table`n`n| Phase | Deliverable | Key Techniques | Assessment Criteria |`n|-------|-------------|----------------|-------------------|`n| 1 - Planning | Project Plan | WBS, COCOMO II, PERT, risk register | Completeness of WBS, estimation |`n| 2 - Requirements | SRS Document | IEEE 830, use cases, MoSCoW | Clarity, consistency, traceability |`n| 3 - Architecture | ADD Document | ADD, ADRs, UML diagrams | Pattern selection, driver satisfaction |`n| 4 - Implementation | Code + Tests | TDD, SOLID, Scrum | Coverage > 70%, code quality |`n| 5 - Testing | Test Plan | BVA, decision tables, automation | Coverage criteria, traceability |`n| 6 - QA | QA Plan | Reviews, metrics, inspections | DRE target, review coverage |`n| 7 - Deployment | Deployment Plan | CI/CD, rollback, migration | Deployment safety, rollback test |`n`n## Quick Reference`n`n| Artefact | Purpose | Cross-Reference |`n|----------|---------|-----------------|`n| Project Charter | Define scope and objectives | WBS, risk register |`n| SRS | Functional and non-functional requirements | Traceability matrix |`n| ADR | Architecture decisions with rationale | Component diagram |`n| Sprint Backlog | Tasks for the implementation Sprint | User stories |`n| Test Plan | Test levels, techniques, automation | Requirements traceability |`n| QA Plan | Quality standards and metrics | Review and inspection procedures |`n| Deployment Plan | Go-live strategy and rollback | CI/CD pipeline configuration |`n`n## Cross-Application Matrix`n`n| Knowledge Area | Capstone Phase | Connection |`n|----------------|----------------|-------------|`n| Process Models | Phase 1 | Select agile or plan-driven approach |`n| Requirements | Phase 2 | Elicitation and specification |`n| Architecture | Phase 3 | Pattern selection and ADRs |`n| Design | Phase 4 | SOLID, coupling and cohesion |`n| Testing | Phase 5 | White-box, black-box, automation |`n| Quality | Phase 6 | Metrics, reviews, CMMI |`n| Configuration | Phase 7 | Version control, CI/CD |`n| Security | All phases | Threat modelling, input validation |`n`n## Chapter Quiz`n`n1. How many phases does the capstone project define?`n   A) Five`n   B) Six`n   C) Seven`n   D) Eight`n`n<details><summary>Answer</summary>**C)** The capstone has seven phases: Planning, Requirements, Architecture, Implementation, Testing, QA, and Deployment.</details>`n`n2. What is the minimum unit test coverage target?`n   A) 50%`n   B) 70%`n   C) 90%`n   D) 100%`n`n<details><summary>Answer</summary>**B)** The capstone targets a minimum of 70% statement coverage for unit tests.</details>`n`n3. Which phase requires the Attribute-Driven Design method?`n   A) Phase 1 - Planning`n   B) Phase 3 - Architecture`n   C) Phase 5 - Testing`n   D) Phase 7 - Deployment`n`n<details><summary>Answer</summary>**B)** Phase 3 (Architectural Design) uses the Attribute-Driven Design (ADD) method.</details>`n`n## Summary`n`nThe capstone project integrates"
$c = $c.Replace($s, $r)
[System.IO.File]::WriteAllText($path, $c, $utf8)
Write-Host "OK 16-capstone.md"

Write-Host "=== Files 13-16 DONE ==="
