#!/usr/bin/env python3
"""
build_india_with_gemini.py

Usage examples:
  # Download datameet CSVs and generate SQL (no Gemini):
  python3 build_india_with_gemini.py --download --output Learn/database/sql/india_with_gemini.sql

  # Same but ask Gemini (Google Generative) to resolve missing district->state mappings (requires GEMINI_API_KEY):
  GEMINI_API_KEY=your_key python3 build_india_with_gemini.py --download --use-gemini --output Learn/database/sql/india_with_gemini.sql

Notes:
 - GEMINI_API_KEY should be provided via environment variable. The script does NOT transmit the key to anyone; it uses it to call the Generative Language REST endpoint.
 - You can set GEMINI_MODEL env var to the model name (default: text-bison-001). Adjust per your Google/Vertex/Generative API setup.
 - The script writes a mapping report JSON next to the output SQL file.
"""

import os
import sys
import argparse
import csv
import json
import time
from pathlib import Path

try:
    import pandas as pd
except Exception:
    print("Please install pandas: pip install pandas")
    sys.exit(1)

try:
    import requests
except Exception:
    print("Please install requests: pip install requests")
    sys.exit(1)

try:
    from rapidfuzz import fuzz
except Exception:
    # rapidfuzz is optional but recommended for fuzzy matching
    def _ratio(a, b):
        a = (a or "").lower()
        b = (b or "").lower()
        # fallback simple ratio
        import difflib
        return int(difflib.SequenceMatcher(None, a, b).ratio() * 100)
    fuzz = type("_FuzzStub", (), {"ratio": staticmethod(_ratio)})

# Datameet candidates
BASE = "https://raw.githubusercontent.com/datameet/maps/master/website/docs/data/csv"
CANDIDATES = {
    "states": [f"{BASE}/statesCensus.csv"],
    "districts": [f"{BASE}/dists.csv"],
    "blocks": [f"{BASE}/blocks.csv", f"{BASE}/blocks.csv"],
    "panchayats": [f"{BASE}/pc_14.csv"],
}

# Normalization helpers
import unicodedata

def normalize_key(k: str):
    return (
        (k or "").strip().lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )


def normalize_name(n: str):
    if not n:
        return ""
    s = str(n).strip().lower()
    s = unicodedata.normalize("NFKD", s)
    s = " ".join(s.split())
    return s

# Minimal Gemini caller - user must set GEMINI_API_KEY env var
GEMINI_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "text-bison-001")


def call_gemini(prompt: str, max_retries=3, wait=1):
    """Call Google's Generative Language REST API (simple wrapper).
    Requires GEMINI_API_KEY in env. Returns plain text answer or None.
    NOTE: Adjust endpoint/model to your account & region.
    """
    if not GEMINI_KEY:
        raise RuntimeError("GEMINI_API_KEY not set")

    url = f"https://generativelanguage.googleapis.com/v1beta2/models/{GEMINI_MODEL}:generateText?key={GEMINI_KEY}"

    body = {
        "prompt": {"text": prompt},
        "maxOutputTokens": 200,
    }

    for attempt in range(1, max_retries + 1):
        try:
            r = requests.post(url, json=body, timeout=30)
            r.raise_for_status()
            doc = r.json()
            # Extract text from response structure
            out = None
            if "candidates" in doc and len(doc["candidates"]) > 0:
                out = doc["candidates"][0].get("content")
            elif "output" in doc and isinstance(doc["output"], dict):
                out = doc["output"].get("text")
            if out:
                return out.strip()
            return None
        except Exception as e:
            if attempt == max_retries:
                raise
            time.sleep(wait * attempt)


def try_read_csv_path(path_or_url: str):
    try:
        if path_or_url.startswith("http://") or path_or_url.startswith("https://"):
            return pd.read_csv(path_or_url, dtype=str)
        else:
            return pd.read_csv(path_or_url, dtype=str)
    except Exception:
        return None


def pick_first_available(list_of_urls_or_paths):
    for u in list_of_urls_or_paths:
        df = try_read_csv_path(u)
        if df is not None and not df.empty:
            return df, u
    return None, None


def detect_column(df, candidates):
    cols = {normalize_key(c): c for c in df.columns}
    for cand in candidates:
        k = normalize_key(cand)
        if k in cols:
            return cols[k]
    # fuzzy match
    for col in df.columns:
        if normalize_key(col) in [normalize_key(cand) for cand in candidates]:
            return col
    return None


def build_sql_out(states_rows, district_rows, blocks_rows, panchayat_rows, output_path, country_id=6):
    parts = []
    parts.append("-- Generated by build_india_with_gemini.py")
    parts.append("SET FOREIGN_KEY_CHECKS=0;")

    # (create statements similar to previous JS script; shortened here)
    parts.append("CREATE TABLE IF NOT EXISTS `countries` (`id` bigint unsigned not null, `name` varchar(255));")
    parts.append("CREATE TABLE IF NOT EXISTS `states` (`id` bigint unsigned not null, `name` varchar(255), `code` varchar(255), `country_id` bigint unsigned not null);")
    parts.append("CREATE TABLE IF NOT EXISTS `districts` (`id` bigint unsigned not null, `name` varchar(255), `code` varchar(255), `state_id` bigint unsigned not null);")
    parts.append("CREATE TABLE IF NOT EXISTS `blocks` (`id` bigint unsigned not null, `name` varchar(255), `code` varchar(255), `district_id` bigint unsigned not null);")
    parts.append("CREATE TABLE IF NOT EXISTS `panchayats` (`id` bigint unsigned not null, `name` varchar(255), `code` varchar(255), `block_id` bigint unsigned not null);")

    # insert country
    parts.append(f"INSERT IGNORE INTO `countries` (`id`,`name`,`code`,`status`) VALUES ({country_id}, 'India', '+91', 1);")

    # states
    if states_rows:
        vals = []
        for s in states_rows:
            vals.append(f"({s['id']}, {sql_escape(s['name'])}, {sql_escape(s.get('code') or s['name'])}, {country_id}, 1)")
        parts.append("INSERT IGNORE INTO `states` (`id`,`name`,`code`,`country_id`,`status`) VALUES\n" + ",\n".join(vals) + ";")

    # districts
    if district_rows:
        vals = []
        for d in district_rows:
            vals.append(f"({d['id']}, {sql_escape(d['name'])}, {sql_escape(d.get('code') or d['name'])}, {d.get('state_id') or 'NULL'}, 1)")
        parts.append("INSERT IGNORE INTO `districts` (`id`,`name`,`code`,`state_id`,`status`) VALUES\n" + ",\n".join(vals) + ";")

    # blocks
    if blocks_rows:
        vals = []
        for b in blocks_rows:
            vals.append(f"({b['id']}, {sql_escape(b['name'])}, {sql_escape(b.get('code') or b['name'])}, {b.get('district_id') or 'NULL'}, 1)")
        parts.append("INSERT IGNORE INTO `blocks` (`id`,`name`,`code`,`district_id`,`status`) VALUES\n" + ",\n".join(vals) + ";")

    # panchayats
    if panchayat_rows:
        vals = []
        for p in panchayat_rows:
            vals.append(f"({p['id']}, {sql_escape(p['name'])}, {sql_escape(p.get('code') or p['name'])}, {p.get('block_id') or 'NULL'}, 1)")
        parts.append("INSERT IGNORE INTO `panchayats` (`id`,`name`,`code`,`block_id`,`status`) VALUES\n" + ",\n".join(vals) + ";")

    parts.append("SET FOREIGN_KEY_CHECKS=1;")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text("\n\n".join(parts), encoding="utf8")


def sql_escape(s):
    if s is None:
        return "NULL"
    s = str(s).replace("\\", "\\\\").replace("'", "''")
    return f"'{s}'"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--states")
    parser.add_argument("--districts")
    parser.add_argument("--blocks")
    parser.add_argument("--panchayats")
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--use-gemini", action="store_true")
    parser.add_argument("--output", default="india_with_gemini.sql")
    args = parser.parse_args()

    # load CSVs
    states_df = None
    districts_df = None
    blocks_df = None
    panchayats_df = None

    if args.states:
        states_df = try_read_csv_path(args.states)
    if args.districts:
        districts_df = try_read_csv_path(args.districts)
    if args.blocks:
        blocks_df = try_read_csv_path(args.blocks)
    if args.panchayats:
        panchayats_df = try_read_csv_path(args.panchayats)

    if args.download:
        if states_df is None:
            states_df, used = pick_first_available(CANDIDATES['states'])
            if states_df is not None:
                print("Downloaded states from:", used)
        if districts_df is None:
            districts_df, used = pick_first_available(CANDIDATES['districts'])
            if districts_df is not None:
                print("Downloaded districts from:", used)
        if blocks_df is None:
            blocks_df, used = pick_first_available(CANDIDATES['blocks'])
            if blocks_df is not None:
                print("Downloaded blocks from:", used)
        if panchayats_df is None:
            panchayats_df, used = pick_first_available(CANDIDATES['panchayats'])
            if panchayats_df is not None:
                print("Downloaded panchayats from:", used)

    if states_df is None and districts_df is None and blocks_df is None and panchayats_df is None:
        print("No CSVs found. Provide paths or use --download.")
        sys.exit(1)

    # process states
    states_rows = []
    state_map_by_name = {}
    next_state_id = 1
    if states_df is not None:
        scode = detect_column(states_df, ["state_code","scode","code","st_code"]) or None
        sname = detect_column(states_df, ["state_name","state","name"]) or None
        for _, r in states_df.iterrows():
            name = (r[sname] if sname and sname in r and not pd_isna(r[sname]) else None) if 'pd' in globals() else (r.get(sname) if sname else None)
            # pandas rows may be Series; safely extract
            if sname in r and not pd_isna(r[sname]):
                name = r[sname]
            elif 'state' in r and not pd_isna(r['state']):
                name = r['state']
            name = (str(name).strip() if name is not None else None)
            code = (r[scode].strip() if scode and scode in r and not pd_isna(r[scode]) else None) if 'pd' in globals() else (r.get(scode) if scode else None)
            if scode in r and not pd_isna(r[scode]):
                code = r[scode]
            idv = next_state_id
            next_state_id += 1
            states_rows.append({"id": idv, "name": name, "code": code})
            if name:
                state_map_by_name[normalize_name(name)] = {"id": idv, "name": name}

    # process districts
    district_rows = []
    next_district_id = 1
    unmatched_districts = []
    if districts_df is not None:
        dname_col = detect_column(districts_df, ["district_name","district","name","dist","dist_name"]) or list(districts_df.columns)[0]
        state_code_col = detect_column(districts_df, ["state","state_name","st","scode","state_code"]) or None
        dcode_col = detect_column(districts_df, ["district_code","dcode","code","districtcode"]) or None
        for _, r in districts_df.iterrows():
            dname = r.get(dname_col) if dname_col in districts_df.columns else None
            dname = (str(dname).strip() if dname is not None and not pd_isna(dname) else None)
            dcode = r.get(dcode_col) if dcode_col and dcode_col in districts_df.columns else None
            dcode = (str(dcode).strip() if dcode is not None and not pd_isna(dcode) else None)
            state_val = r.get(state_code_col) if state_code_col and state_code_col in districts_df.columns else None
            state_val = (str(state_val).strip() if state_val is not None and not pd_isna(state_val) else None)

            state_id = None
            if state_val:
                # try exact name match
                n = normalize_name(state_val)
                if n in state_map_by_name:
                    state_id = state_map_by_name[n]['id']
                else:
                    # fuzzy match
                    best = None
                    best_score = 0
                    for sname, s in state_map_by_name.items():
                        score = fuzz.ratio(n, sname)
                        if score > best_score:
                            best_score = score
                            best = s
                    if best and best_score > 85:
                        state_id = best['id']
            # if no state resolved and --use-gemini, we'll attempt later
            idv = next_district_id
            next_district_id += 1
            district_rows.append({"id": idv, "name": dname, "code": dcode, "state_id": state_id})
            if state_id is None:
                unmatched_districts.append({"id": idv, "name": dname, "code": dcode})

    # If user requested Gemini and we have unmatched districts, ask Gemini for state names
    gemini_map_cache = {}
    if args.use_gemini and GEMINI_KEY and unmatched_districts:
        print(f"Trying Gemini for {len(unmatched_districts)} unmatched districts (this may use API quota)")
        for item in unmatched_districts:
            dname = item['name']
            if not dname:
                continue
            # cache key
            key = normalize_name(dname)
            if key in gemini_map_cache:
                suggested = gemini_map_cache[key]
            else:
                prompt = f"Which Indian state does the district named '{dname}' belong to? Answer only the state name, nothing else. If uncertain, reply 'UNKNOWN'."
                try:
                    ans = call_gemini(prompt)
                except Exception as e:
                    print("Gemini call failed:", e)
                    ans = None
                suggested = None
                if ans:
                    # pick first line
                    ans_line = ans.splitlines()[0].strip()
                    if ans_line and ans_line.upper() != 'UNKNOWN':
                        suggested = ans_line
                gemini_map_cache[key] = suggested
                # be polite with API
                time.sleep(0.3)

            if suggested:
                # fuzzy match suggested state name to known states
                best = None
                best_score = 0
                norm_suggested = normalize_name(suggested)
                for sname, s in state_map_by_name.items():
                    score = fuzz.ratio(norm_suggested, sname)
                    if score > best_score:
                        best_score = score
                        best = s
                if best and best_score > 80:
                    # update district_rows
                    for d in district_rows:
                        if d['id'] == item['id']:
                            d['state_id'] = best['id']
                            break

    # blocks (basic mapping similar to JS but simplified)
    blocks_rows = []
    if blocks_df is not None:
        bname_col = detect_column(blocks_df, ["block_name","block","name","tehsil","taluka"]) or list(blocks_df.columns)[0]
        bcode_col = detect_column(blocks_df, ["block_code","bcode","code"]) or None
        dname_col_guess = detect_column(blocks_df, ["district","district_name","dist","districtname"]) or None
        next_block_id = 1
        for _, r in blocks_df.iterrows():
            bname = r.get(bname_col) if bname_col in blocks_df.columns else None
            bname = (str(bname).strip() if bname is not None and not pd_isna(bname) else None)
            bcode = r.get(bcode_col) if bcode_col and bcode_col in blocks_df.columns else None
            bcode = (str(bcode).strip() if bcode is not None and not pd_isna(bcode) else None)
            district_ref = r.get(dname_col_guess) if dname_col_guess and dname_col_guess in blocks_df.columns else None
            district_ref = (str(district_ref).strip() if district_ref is not None and not pd_isna(district_ref) else None)
            district_id = None
            if district_ref:
                # try to find district by name
                norm = normalize_name(district_ref)
                best = None
                best_score = 0
                for d in district_rows:
                    score = fuzz.ratio(norm, normalize_name(d['name'])) if d['name'] else 0
                    if score > best_score:
                        best_score = score
                        best = d
                if best and best_score > 85:
                    district_id = best['id']
            blocks_rows.append({"id": next_block_id, "name": bname, "code": bcode, "district_id": district_id})
            next_block_id += 1

    # panchayats - often pc_14 is not panchayats; skip if it looks like pc
    panchayat_rows = []
    if panchayats_df is not None:
        sample_keys = " ".join(panchayats_df.columns).lower()
        if any(k in sample_keys for k in ["pc no","pc name","pc type"]):
            print("Panchayat input looks like parliamentary constituencies (pc_14). Skipping panchayats.")
        else:
            pname_col = detect_column(panchayats_df, ["panchayat_name","name","gp","village","panchayat"]) or list(panchayats_df.columns)[0]
            pcode_col = detect_column(panchayats_df, ["panchayat_code","pcode","code"]) or None
            bname_guess = detect_column(panchayats_df, ["block","block_name","tehsil","taluka"]) or None
            next_pid = 1
            for _, r in panchayats_df.iterrows():
                pname = r.get(pname_col) if pname_col in panchayats_df.columns else None
                pname = (str(pname).strip() if pname is not None and not pd_isna(pname) else None)
                pcode = r.get(pcode_col) if pcode_col and pcode_col in panchayats_df.columns else None
                pcode = (str(pcode).strip() if pcode is not None and not pd_isna(pcode) else None)
                bref = r.get(bname_guess) if bname_guess and bname_guess in panchayats_df.columns else None
                bref = (str(bref).strip() if bref is not None and not pd_isna(bref) else None)
                block_id = None
                if bref:
                    best = None
                    best_score = 0
                    for b in blocks_rows:
                        if not b['name']:
                            continue
                        score = fuzz.ratio(normalize_name(bref), normalize_name(b['name']))
                        if score > best_score:
                            best_score = score
                            best = b
                    if best and best_score > 85:
                        block_id = best['id']
                if not pname and not pcode:
                    continue
                panchayat_rows.append({"id": next_pid, "name": pname, "code": pcode, "block_id": block_id})
                next_pid += 1

    # output SQL and mapping report
    out_path = args.output
    build_sql_out(states_rows, district_rows, blocks_rows, panchayat_rows, out_path)
    report = {
        "unmatched_districts": [d for d in district_rows if not d.get('state_id')],
        "unmatched_blocks": [b for b in blocks_rows if not b.get('district_id')],
        "unmatched_panchayats": [p for p in panchayat_rows if not p.get('block_id')],
        "gemini_cache": gemini_map_cache,
    }
    Path(out_path + ".mapping-report.json").write_text(json.dumps(report, indent=2), encoding="utf8")
    print("SQL written to:", out_path)
    print("Mapping report written to:", out_path + ".mapping-report.json")


if __name__ == '__main__':
    main()
