mindmap
  root((JavaScript Basics))
    Data Types
      Primitive string number boolean null undefined symbol bigint
      Object
      Type Coercion
    Variables
      var
      let
      const
      Scope Global vs Block vs Function
    Functions
      Function Declaration
      Function Expression
      Arrow Functions
      Closures
      IIFE
      Callbacks
    Objects
      Object Literal
      Constructor Function
      Prototype Chain
      this Keyword
      Factory Functions
    Control Flow
      if else
      switch
      for while do while
      forEach for of for in
    Error Handling
      try catch finally
      throw
      Custom Errors
