mindmap
  root((ES6+ Features))
    Variable Declarations
      let Block Scoped
      const Immutable Binding
      Temporal Dead Zone
    Arrow Functions
      Lexical this
      Implicit Return
      No arguments Object
    Template Literals
      String Interpolation
      Multi-line Strings
      Tagged Templates
    Destructuring
      Array Destructuring
      Object Destructuring
      Default Values
      Nested Destructuring
    Spread & Rest
      Spread Operator
      Rest Parameters
      Array Copy
      Object Merge
    Classes
      class Syntax
      constructor
      extends Inheritance
      super
      Static Methods
      Private Fields
    Modules
      export default
      named export
      import
      Dynamic import
    Promises & Async
      Promise States
      then catch finally
      async await
      Promise all race allSettled
    Collections
      Map
      Set
      WeakMap
      WeakSet
    Symbols & Iterators
      Symbol
      for of
      Iterators
      Generators
