mindmap
  root((Aptitude Topics))
    Quantitative
      Number Systems
      Percentages
      Time Speed Distance
      Profit & Loss
      Probability
      Permutations
    Logical
      Blood Relations
      Syllogisms
      Seating Arrangement
      Data Sufficiency
      Puzzles
    Verbal
      Reading Comprehension
      Grammar
      Vocabulary
      Sentence Correction
    Coding
      Problem Solving
      Algorithms
      Data Structures
      SQL Queries
