mindmap
  root((Build Tools and Packaging))
    Build vs Package
      Build Phase
        Compilation
        Minification
        Asset Compilation
        Code Generation
      Package Phase
        Executable Assembly
        Metadata Addition
        Dependency Declarations
        Version Tagging
    Language Tools
      JavaScript TypeScript
        npm
        yarn
        pnpm
        webpack
        esbuild
      Python
        pip
        poetry
        setuptools
      Java
        Maven
        Gradle
      Go
        go mod
      Rust
        Cargo
      .NET
        NuGet
        MSBuild
    Artifact Repositories
      Nexus
      JFrog Artifactory
      GitHub Packages
      Docker Hub
      ECR ACR GCR
    Versioning
      SemVer
        MAJOR Breaking
        MINOR Feature
        PATCH Bug Fix
      CalVer
      ZeroVer
    SBOM
      SPDX
      CycloneDX
      Generation Tools
        Syft
        Trivy