mindmap
  root(("Python OOP"))
    Class Basics
      class keyword
      __init__ constructor
      self parameter
      Class vs Instance attributes
    Method Types
      Instance method
        self, mutable state
      @classmethod
        cls, alternative constructors
      @staticmethod
        Utility, no self/cls
      @property
        Computed attributes
        Getter / Setter / Deleter
    Special Methods
      __str__ / __repr__
      __eq__ / __hash__
      __call__
      __lt__ / __gt__
    Inheritance
      super call
      MRO resolution
      Mixins
    Data Classes
      @dataclass
      Auto __init__ __repr__ __eq__
      frozen / order / slots
    Advanced
      __slots__ memory opt
      Name mangling __attr
      Descriptors
      Abstract base classes
